"""empty message

Revision ID: 3a5b5c7ca7fb
Revises: 7e835c36e8d8
Create Date: 2023-08-16 22:22:47.879970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5b5c7ca7fb'
down_revision = '7e835c36e8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cat_to_prod',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    op.create_table('category_tree',
    sa.Column('parent_cat_id', sa.Integer(), nullable=True),
    sa.Column('child_cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_cat_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['parent_cat_id'], ['category.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_tree')
    op.drop_table('cat_to_prod')
    op.drop_table('product')
    op.drop_table('category')
    # ### end Alembic commands ###
