"""empty message

Revision ID: 606cc86d2a20
Revises: 6e7df2cda701
Create Date: 2023-09-06 23:15:33.587852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606cc86d2a20'
down_revision = '6e7df2cda701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pass_reset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pass_reset', schema=None) as batch_op:
        batch_op.drop_column('complete')

    # ### end Alembic commands ###
