"""empty message

Revision ID: 6e7df2cda701
Revises: baf4318c4e78
Create Date: 2023-09-06 22:58:40.287569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7df2cda701'
down_revision = 'baf4318c4e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pass_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reset_id', sa.String(length=36), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reset_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pass_reset')
    # ### end Alembic commands ###
