"""empty message

Revision ID: 7e835c36e8d8
Revises: f9cefe3a9e90
Create Date: 2023-08-14 22:34:39.020164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e835c36e8d8'
down_revision = 'f9cefe3a9e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_to_post',
    sa.Column('parent_post_id', sa.Integer(), nullable=True),
    sa.Column('child_post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['parent_post_id'], ['post.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_to_post')
    op.drop_table('post')
    # ### end Alembic commands ###
